resolver: lts-8.11

packages:
- '.'
- location: '../common'
  extra-dep: false  # run the test suite for this package
- location: '../prelude'
  extra-dep: false  # run the test suite for this package
- location:
    git: https://github.com/zerobuzz/lentil.git
    commit: 3fcde2423b176c6addf86f038dbf3e39db771410
  extra-dep: true
- location:
    git: https://github.com/andorp/elim.git
    commit: 558fc65a4033577092214c5e2defd47805678b97
  extra-dep: true
- location:
    git: https://github.com/zerobuzz/servant-cookie-session.git
    commit: 29df957fe7826632254fdbb213883caad0052fd9
  extra-dep: true

extra-deps:
- basic-sop-0.2.0.1
- functor-infix-0.0.4
- i18n-0.4.0.0
- json-sop-0.2.0.2
- lens-sop-0.2.0.1

- fingertree-tf-0.1.0.0
- lens-properties-4.11

- wai-extra-3.0.20.0
  # LTS Haskell 8.19:            3.0.19.1
  # Stackage Nightly 2017-06-22: 3.0.19.1
  # Latest on Hackage:           3.0.20.0

- persistent-2.7.0
- persistent-sqlite-2.6.2
- users-persistent-0.5.0.2
- esqueleto-2.5.3
  # persistent packages have been tweaked to younger-than lts-8.11 in
  # order to fix #291.  not sure whether it'll work yet.

flags: {}

extra-package-dbs: []
