resolver:
  name: stack-snapshot
  location: ../../stack-snapshot.yaml

packages:
- '.'
- location: '../common'
  extra-dep: false  # run the test suite for this package
- location: '../prelude'
  extra-dep: false  # run the test suite for this package
- location:
    git: https://github.com/zerobuzz/lentil.git
    commit: 3fcde2423b176c6addf86f038dbf3e39db771410
  extra-dep: true
- location:
    git: https://github.com/andorp/elim.git
    commit: 558fc65a4033577092214c5e2defd47805678b97
  extra-dep: true
- location:
    git: https://github.com/ekmett/lens.git
    commit: 7d16b2b8715ce2123f1c4f5cb5330416d1967e9b
  extra-dep: true
  subdirs:
  - lens-properties  # the hackage version has outdated version bounds (we have transformers-0.5.2.0)
- location:
    git: https://github.com/zerobuzz/servant-cookie-session.git
    commit: 7186ca8c53778822b45bd5d3d71945add778770f
  extra-dep: true
- location:
    git: https://github.com/liqula/wai
    commit: ed575fb2f0aa9fba37c32e93bebff2566e9a2dd4
  extra-dep: true
  subdirs:
  - wai-extra

extra-deps:
- lens-properties-4.11

flags: {}

extra-package-dbs: []
