resolver: lts-9.6

packages:
- '.'
- location: '../common'
  extra-dep: false  # run the test suite for this package
- location: '../prelude'
  extra-dep: false  # run the test suite for this package
- location:
    git: https://github.com/zerobuzz/lentil.git
    commit: 3fcde2423b176c6addf86f038dbf3e39db771410
  extra-dep: true
- location:
    git: https://github.com/andorp/elim.git
    commit: 558fc65a4033577092214c5e2defd47805678b97
  extra-dep: true
- location:
    git: https://github.com/zerobuzz/servant-cookie-session.git
    commit: 29df957fe7826632254fdbb213883caad0052fd9
  extra-dep: true

extra-deps:
- basic-sop-0.2.0.2
- fingertree-tf-0.1.0.0
- i18n-0.4.0.0
- json-sop-0.2.0.3
- lens-sop-0.2.0.2
- users-persistent-0.5.0.2

flags: {}

extra-package-dbs: []
