resolver: lts-7.1

packages:
- '.'
- location: '../common'
  extra-dep: false  # run the test suite for this package
- location: '../prelude'
  extra-dep: false  # run the test suite for this package
- location:
    git: https://github.com/andorp/lentil.git
    commit: 61a1c8421388c525ff4d98b59b3cf3b4ca5f5ad2
  extra-dep: true
- location:
    git: https://github.com/andorp/elim.git
    commit: 558fc65a4033577092214c5e2defd47805678b97
  extra-dep: true
- location:
    git: https://github.com/bgamari/html-parse.git
    commit: ebdd5fa3fa5a0d3c22602bec15059e821ad10ec4
  extra-dep: true
- location:
    git: https://github.com/zerobuzz/servant-cookie-session.git
    commit: 7186ca8c53778822b45bd5d3d71945add778770f
  extra-dep: true

extra-deps:
- basic-sop-0.2.0.0
- from-sum-0.2.1.0
- functor-infix-0.0.4
- graphviz-2999.18.1.2
- heterocephalus-1.0.4.0
- html-parse-0.2.0.0
- json-sop-0.2.0.1
- lens-sop-0.2.0.1
- users-persistent-0.5.0.0
- xml-html-qq-0.1.0.1

flags: {}

extra-package-dbs: []
