resolver: lts-7.1

packages:
- refine-prelude
- refine-common
- refine-backend
- refine-frontend
- location:
    git: https://github.com/andorp/lentil.git
    commit: 61a1c8421388c525ff4d98b59b3cf3b4ca5f5ad2
  extra-dep: true
- location:
    git: https://github.com/andorp/elim.git
    commit: 558fc65a4033577092214c5e2defd47805678b97
  extra-dep: true
- location:
    git: https://github.com/bgamari/html-parse.git
    commit: ebdd5fa3fa5a0d3c22602bec15059e821ad10ec4
  extra-dep: true

extra-deps:
- basic-sop-0.2.0.0
- functor-infix-0.0.4
- haskell-src-exts-1.19.1
- hlint-1.9.39
- html-parse-0.2.0.0
- json-sop-0.2.0.1
- lens-sop-0.2.0.1
- react-flux-1.2.3
- react-flux-servant-0.1.1

flags: {}

extra-package-dbs: []
