name:                refine-backend
version:             0.0.0.0
synopsis:            'Refine backend'
description:         Please see README.md
homepage:            https://github.com/fisx/refine
license:             AGPL
license-file:        LICENSE
author:
  - Andor Penzes <andor.penzes@gmail.com>
  - Matthias Fischmann <mf@zerobuzz.net>
  - Nicole Rauch <info@nicole-rauch.de>
maintainer:          mf@zerobuzz.net
copyright:           2017-2022 zerobuzz.net
category:            Web

default-extensions:
  - DataKinds
  - DeriveFunctor
  - DeriveGeneric
  - ExplicitForAll
  - GADTs
  - GeneralizedNewtypeDeriving
  - OverloadedStrings
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeOperators

ghc-options: -Wall -Werror

dependencies:
  - base
  - darcs
  - elim
  - lens
  - lentil
  - monad-logger
  - mtl
  - natural-transformation
  - persistent
  - persistent-sqlite
  - persistent-template
  - refine-common
  - resourcet
  - servant
  - servant-server
  - string-conversions
  - text
  - warp

library:
  source-dirs:
    - src

executables:
  refine-backend:
    main: Main.hs
    source-dirs:
      - src
      - app

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - containers
      - directory
      - hspec
      - hspec-core
      - hspec-discover
      - QuickCheck
