name:                refine-backend
version:             0.0.0.0
synopsis:            'Refine backend'
description:         Please see README.md
homepage:            https://github.com/fisx/refine
license:             AGPL
license-file:        LICENSE
author:
  - Andor Penzes <andor.penzes@gmail.com>
  - Matthias Fischmann <mf@zerobuzz.net>
  - Nicole Rauch <info@nicole-rauch.de>
maintainer:          mf@zerobuzz.net
copyright:           2017-2022 zerobuzz.net
category:            Web

ghc-options: -Wall -Werror

dependencies:
  - base
  - darcs
  - directory
  - elim
  - filepath
  - functor-infix
  - lens
  - lentil
  - monad-logger
  - mtl
  - natural-transformation
  - persistent
  - persistent-sqlite
  - persistent-template
  - random
  - refine-prelude
  - refine-common
  - resourcet
  - servant
  - servant-server
  - string-conversions
  - text
  - uuid
  - warp

library:
  source-dirs:
    - src

executables:
  refine-backend:
    main: Main.hs
    source-dirs:
      - src
      - app

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - aeson
      - containers
      - directory
      - hspec
      - hspec-core
      - hspec-discover
      - hspec-wai
      - http-api-data
      - http-types
      - QuickCheck
      - temporary
      - transformers
      - wai-extra
