name:                refine-common
version:             0.0.0.0
synopsis:            'Refine common parts for frontend and backend'
description:         Please see README.md
homepage:            https://github.com/fisx/refine
license:             AGPL
license-file:        LICENSE
author:
  - Andor Penzes <andor.penzes@gmail.com>
  - Matthias Fischmann <mf@zerobuzz.net>
  - Nicole Rauch <info@nicole-rauch.de>
maintainer:          mf@zerobuzz.net
copyright:           2017-2022 zerobuzz.net
category:            Web

default-extensions:
  - DataKinds
  - DeriveGeneric
  - ExplicitForAll
  - GADTs
  - OverloadedStrings
  - RankNTypes
  - ScopedTypeVariables
  - TemplateHaskell
  - TypeApplications
  - TypeFamilies
  - TypeOperators

ghc-options: -Wall -Werror

dependencies:
  - aeson
  - base
  - basic-sop
  - deepseq
  - generics-sop
  - http-api-data
  - json-sop
  - lens
  - natural-transformation
  - refine-prelude
  - servant
  - string-conversions
  - time

library:
  source-dirs:
    - src

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec
      - hspec-core
      - hspec-discover
      - QuickCheck
    ghc-options:
      - -fno-warn-orphans
