resolver: lts-7.1

packages:
- '.'
- '../refine-prelude'
- location:
    git: https://github.com/andorp/elim.git
    commit: 558fc65a4033577092214c5e2defd47805678b97
  extra-dep: true
- location:
    git: https://github.com/bgamari/html-parse.git
    commit: ebdd5fa3fa5a0d3c22602bec15059e821ad10ec4
  extra-dep: true

extra-deps:
- basic-sop-0.2.0.0
- functor-infix-0.0.4
- html-parse-0.2.0.0
- json-sop-0.2.0.1
- lens-sop-0.2.0.1

flags: {}

extra-package-dbs: []
