resolver: lts-7.14

packages:
- '.'
- '../refine-prelude'
- location:
    git: https://github.com/andorp/elim.git
    commit: 558fc65a4033577092214c5e2defd47805678b97

extra-deps:
- basic-sop-0.2.0.0
- lens-sop-0.2.0.1
- json-sop-0.2.0.1

flags: {}

extra-package-dbs: []
