resolver: lts-8.11

packages:
- '.'
- location: '../prelude'
  extra-dep: true
- location:
    git: https://github.com/ekmett/lens.git
    commit: 7d16b2b8715ce2123f1c4f5cb5330416d1967e9b
  extra-dep: true
  subdirs:
  - lens-properties  # the hackage version has outdated version bounds (we have transformers-0.5.2.0)

extra-deps:
- basic-sop-0.2.0.1
- fingertree-tf-0.1.0.0
- i18n-0.4.0.0
- json-sop-0.2.0.2
- lens-properties-4.11
- lens-sop-0.2.0.1

flags: {}

extra-package-dbs: []
