resolver: lts-7.1
#resolver: lts-6.30

packages:
- '.'
- location: '../prelude'
  extra-dep: true
- location:
    git: https://github.com/bgamari/html-parse.git
    commit: ebdd5fa3fa5a0d3c22602bec15059e821ad10ec4
  extra-dep: true

extra-deps:
- basic-sop-0.2.0.0
- from-sum-0.2.1.0
- functor-infix-0.0.4
- heterocephalus-1.0.4.0
- html-parse-0.2.0.0
- i18n-0.4.0.0
- json-sop-0.2.0.1
- lens-sop-0.2.0.1
- partial-order-0.1.2
- xml-html-qq-0.1.0.1

flags: {}

extra-package-dbs: []
