resolver:
  name: stack-snapshot
  location: ../../stack-snapshot.yaml

packages:
- '.'
- location: '../prelude'
  extra-dep: true
- location:
    git: https://github.com/ekmett/lens.git
    commit: 7d16b2b8715ce2123f1c4f5cb5330416d1967e9b
  extra-dep: true
  subdirs:
  - lens-properties  # the hackage version has outdated version bounds (we have transformers-0.5.2.0)

extra-deps:
- lens-properties-4.11

flags: {}

extra-package-dbs: []
