resolver:
  name: stack-snapshot
  location: ../../stack-snapshot.yaml

# START __GHCJS__
# see also: stack-no-js.yaml

compiler: ghcjs-0.2.1.9008011_ghc-8.0.2
compiler-check: match-exact

# for custom ghcjs compilers, set version like this:
# ghcjs-`ghcjs --numeric-version`_ghc-`ghcjs --numeric-ghc-version`
#export PATH=/home/mf/src/ghcjs/.cabal-sandbox/bin:$PATH
#stack build --fast --system-ghc
#compiler: ghcjs-0.2.1_ghc-8.0.2
#compiler-check: match-exact

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9008011_ghc-8.0.2:
        url: https://github.com/zerobuzz/ghcjs-stack-dist/raw/master/ghcjs-0.2.1.9008011.tar.gz
        sha1: a72a5181124baf64bcd0e68a8726e65914473b3b
      ghcjs-0.2.1.9007019_ghc-8.0.1:
        url: http://ghcjs.tolysz.org/ghc-8.0-2017-02-05-lts-7.19-9007019.tar.gz
        sha1: d2cfc25f9cda32a25a87d9af68891b2186ee52f9
      ghcjs-0.2.1.9007013_ghc-8.0.1:
        url: http://ghcjs.tolysz.org/ghc-8.0-2016-12-18-lts-7.13-9007013.tar.gz
        sha1: 530c4ee5e19e2874e128431c7ad421e336df0303

# END __GHCJS__

packages:
- '.'
- location: '../common'
  extra-dep: true
- location: '../prelude'
  extra-dep: true
- location:
    git: https://github.com/liqula/react-hs
    commit: f6e1b357fbc233f6b3318bf0ea74480c7fbdc88c
  extra-dep: true
  subdirs:
  - react-hs

extra-deps:
- react-hs-0.1.0
- refine-common-0.0.0.0
- language-css-0.0.3
- fingertree-tf-0.1.0.0
