resolver: lts-6.30
compiler: ghcjs-0.2.0.9006030_ghc-7.10.3
compiler-check: match-exact

packages:
- '.'
- location: '../common'
  extra-dep: true
- location: '../prelude'
  extra-dep: true
- location:
    git: https://github.com/bgamari/html-parse.git
    commit: ebdd5fa3fa5a0d3c22602bec15059e821ad10ec4
  extra-dep: true

extra-deps:
- aeson-extra-0.4.0.0
- basic-sop-0.2.0.0
- functor-infix-0.0.4
- html-parse-0.2.0.0
- json-sop-0.2.0.1
- lens-sop-0.2.0.1
- react-flux-1.2.3
- react-flux-servant-0.1.1
- recursion-schemes-5.0.1
- refine-common-0.0.0.0
- string-0.4.0

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.9006030_ghc-7.10.3:
         url: http://ghcjs.tolysz.org/lts-6.30-9006030.tar.gz
         sha1: 2371e2ffe9e8781808b7a04313e6a0065b64ee51
