resolver: lts-7.19

compiler: ghcjs-0.2.1.9007019_ghc-8.0.1
compiler-check: match-exact

# for custom ghcjs compilers, set version like this:
# ghcjs-`ghcjs --numeric-version`_ghc-`ghcjs --numeric-ghc-version`
#export PATH=/home/mf/src/ghcjs/.cabal-sandbox/bin:$PATH
#stack build --fast --system-ghc
#compiler: ghcjs-0.2.1_ghc-8.0.2
#compiler-check: match-exact

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9007019_ghc-8.0.1:
        url: http://ghcjs.tolysz.org/ghc-8.0-2017-02-05-lts-7.19-9007019.tar.gz
        sha1: d2cfc25f9cda32a25a87d9af68891b2186ee52f9
      ghcjs-0.2.1.9007013_ghc-8.0.1:
        url: http://ghcjs.tolysz.org/ghc-8.0-2016-12-18-lts-7.13-9007013.tar.gz
        sha1: 530c4ee5e19e2874e128431c7ad421e336df0303

packages:
- '.'
- location: '../common'
  extra-dep: true
- location: '../prelude'
  extra-dep: true
- location:
    git: https://github.com/well-typed/basic-sop.git
    commit: 1e98bc7829e8c4ca5fe408ed5bfc7ad2a988d88c
  extra-dep: true
- location:
    git: https://github.com/bgamari/html-parse.git
    commit: ebdd5fa3fa5a0d3c22602bec15059e821ad10ec4
  extra-dep: true
- location:
    git: https://github.com/liqula/react-flux
    commit: fc09983c313536d51278f9fa3bdbc10dd9d1149e
  extra-dep: true
- location:
    git: https://github.com/liqula/react-flux-servant
    commit: 029581885116d71e7e4441a42b7789ee2e75e3a6
  extra-dep: true

extra-deps:
- aeson-extra-0.4.0.0
- basic-sop-0.2.0.0
- functor-infix-0.0.4
- html-parse-0.2.0.0
- i18n-0.4.0.0
- json-sop-0.2.0.1
- lens-sop-0.2.0.1
- react-flux-1.3.0
- react-flux-servant-0.2.0
- recursion-schemes-5.0.1
- refine-common-0.0.0.0
- string-0.4.0
