# this is the stack.yaml file for running the frontend in ghci.  many
# things won't work (ffi functions are all replaced by 'undefined'
# stubs), but the type checker should be able to help you with less
# lag than ghcjs.
#
# to get going, try this:
#
# stack --stack-yaml=stack-no-js.yaml test --fast
# stack --stack-yaml=stack-no-js.yaml exec -- ghci -isrc -itest -i../common/src -i../prelude/src test/Main.hs
#
# to compile with ghcjs, call `nix-build build.nix`.

resolver: lts-8.11

packages:
- '.'
- location: '../common'
  extra-dep: true
- location: '../prelude'
  extra-dep: true
- location:
    git: https://github.com/liqula/react-hs
    commit: 20afefb10e2d8f9a126bc62d2058fe4735b3a31c
  extra-dep: true
  subdirs:
  - react-hs

extra-deps:
- basic-sop-0.2.0.1
- fingertree-tf-0.1.0.0
- generics-sop-0.3.1.0
- i18n-0.4.0.0
- json-sop-0.2.0.2
- language-css-0.0.3
- lens-sop-0.2.0.1
- react-hs-0.1.0
