# regarding downgrading to lts-6.30, see #217.

resolver: lts-7.1
compiler: ghcjs-0.2.1.9007001_ghc-8.0.1
compiler-check: match-exact
# for custom ghcjs compilers, set version like this:
# ghcjs-`ghcjs --numeric-version`_ghc-`ghcjs --numeric-ghc-version`

packages:
- '.'
- location: '../common'
  extra-dep: true
- location: '../prelude'
  extra-dep: true
- location:
    git: https://github.com/bgamari/html-parse.git
    commit: ebdd5fa3fa5a0d3c22602bec15059e821ad10ec4
  extra-dep: true

extra-deps:
- aeson-extra-0.4.0.0
- basic-sop-0.2.0.0
- functor-infix-0.0.4
- html-parse-0.2.0.0
- i18n-0.4.0.0
- json-sop-0.2.0.1
- lens-sop-0.2.0.1
- react-flux-1.2.3
- react-flux-servant-0.1.1
- recursion-schemes-5.0.1
- refine-common-0.0.0.0
- string-0.4.0

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9007001_ghc-8.0.1:
        url: http://tolysz.org/ghcjs/ghc-8.0-2016-09-26-lts-7.1-9007001-mem.tar.gz
        sha1: e640724883238593e2d2f7f03991cb413ec0347b
