name:        refine-prelude
version:     0.0.0.0
description: Please see README.md
license:     AGPL
copyright:   2017-2022 zerobuzz UG (haftungsbeschränkt)
author: >
  Andor Penzes <andorp@posteo.net>,
  Matthias Fischmann <mf@zerobuzz.net>,
  Nicole Rauch <info@nicole-rauch.de>
maintainer:  mf@zerobuzz.net

data-files:
  - README.md
  - docs/*

ghc-options: -j -Wall -Wno-redundant-constraints -Werror

dependencies:
  - aeson
  - base
  - basic-sop
  - bytestring
  - containers
  - data-default
  - deepseq
  - directory
  - functor-infix
  - generics-sop
  - http-api-data
  - json-sop
  - lens
  - monad-control
  - mtl
  - natural-transformation
  - process
  - servant
  - stm
  - string-conversions
  - template-haskell
  - text
  - time
  - transformers
  - unordered-containers

library:
  source-dirs: src

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - base
      - hspec
      - hspec-core
      - QuickCheck
      - quickcheck-instances
      - refine-prelude
