name:        refine-prelude
version:     0.0.0.0
description: Please see README.md
license:     AGPL
copyright:   2017-2022 zerobuzz UG (haftungsbeschränkt)
author: >
  Andor Penzes <andorp@posteo.net>,
  Matthias Fischmann <mf@zerobuzz.net>,
  Nicole Rauch <info@nicole-rauch.de>
maintainer:  mf@zerobuzz.net

data-files:
  - README.md
  - docs/*

ghc-options: -j -Wall -Werror

dependencies:
  - aeson
  - base
  - basic-sop
  - containers
  - deepseq
  - generics-sop
  - http-api-data
  - json-sop
  - lens
  - mtl
  - natural-transformation
  - process
  - servant
  - string-conversions
  - template-haskell
  - time

library:
  source-dirs: src

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - base
      - hspec
      - hspec-core
      - hspec-discover
      - QuickCheck
      - quickcheck-instances
      - refine-prelude
